language: python

dist: trusty

python:
  - 3.4
  - 3.5
  - 3.6
  - nightly

git:
  depth: 3

install:
  - pip3 install numpy matplotlib

script:
  - for in_file in noisy_data/*.txt; do out_file=denoised_$(basename $in_file); ./denoise -i $in_file -o $out_file -u 20.0; diff $out_file .travis/$out_file; done

notifications:
  email:
    recipients:
      - diego@assencio.com
    on_success: change
    on_failure: always
